version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: videoflix_worker
    command: python manage.py rqworker default
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - videoflix_media:/app/media
      - videoflix_static:/app/static

  mailhog:
    image: mailhog/mailhog
    container_name: videoflix_mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
