# Generated by Django 5.2.1 on 2025-06-23 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('original_file', models.FileField(max_length=255, upload_to='videos/original/')),
                ('thumbnail', models.ImageField(max_length=255, upload_to='videos/thumbnails/')),
                ('video_180p', models.FileField(blank=True, max_length=255, null=True, upload_to='videos/180p/')),
                ('video_360p', models.FileField(blank=True, max_length=255, null=True, upload_to='videos/360p/')),
                ('video_720p', models.FileField(blank=True, max_length=255, null=True, upload_to='videos/720p/')),
                ('video_1080p', models.FileField(blank=True, max_length=255, null=True, upload_to='videos/1080p/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('documentary', 'Documentary'), ('horror', 'Horror'), ('sci-fi', 'Science Fiction'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('animation', 'Animation'), ('fantasy', 'Fantasy')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_seconds', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoflix.video')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
    ]
