# Generated by Django 5.2.1 on 2025-06-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='videos/thumbnails/'),
        ),
    ]
