# Generated by Django 5.2.1 on 2025-06-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='upload_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_published',
        ),
        migrations.AddField(
            model_name='video',
            name='original_file',
            field=models.FileField(default='undefined', upload_to='videos/original/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='undefined', upload_to='videos/thumbnails/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_180p',
            field=models.FileField(blank=True, null=True, upload_to='videos/180p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_360p',
            field=models.FileField(blank=True, null=True, upload_to='videos/360p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(),
        ),
    ]
