# Generated by Django 5.2.1 on 2025-06-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0002_rename_upload_date_video_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='original_file',
            field=models.FileField(max_length=255, upload_to='videos/original/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(max_length=255, upload_to='videos/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_1080p',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos/1080p/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_180p',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos/180p/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_360p',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos/360p/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_720p',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos/720p/'),
        ),
    ]
