# Generated by Django 5.2.1 on 2025-06-04 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0004_videoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('documentary', 'Documentary'), ('horror', 'Horror'), ('sci-fi', 'Science Fiction'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('animation', 'Animation'), ('fantasy', 'Fantasy')], default='action', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
