# Generated by Django 5.2.1 on 2025-06-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0005_video_genre_video_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
    ]
