# Generated by Django 5.2.1 on 2025-06-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix', '0006_remove_video_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(),
        ),
    ]
