# Generated by Django 5.2.1 on 2025-06-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='anonymous', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
